Import('*')

SimObject('local_detector.py', sim_objects=['CRICMILocalDetector'])
Source('cricmi_local_detector.cc')

SimObject('cricmi_global_detector.py', sim_objects=['CRICMIGlobalDetector'])
Source('cricmi_global_detector.cc')